scrape_configs:
- job_name: cadvisor
  scrape_interval: 5s
  static_configs:
  - targets:
    - cadvisor:8080
- job_name: node
  scrape_interval: 5s
  static_configs:
  - targets:
    - node_exporter:9100
- job_name: api
  metrics_path: /metrics
  static_configs:
    - targets:
        - host.docker.internal:8000
